"""Initial schema

Revision ID: bb486ea370b1
Revises: 
Create Date: 2026-03-25 23:25:43.208071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb486ea370b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schema
    op.execute('CREATE SCHEMA IF NOT EXISTS loan_db')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole', schema='loan_db'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='loan_db'
    )
    op.create_index(op.f('ix_loan_db_users_email'), 'users', ['email'], unique=True, schema='loan_db')
    op.create_index(op.f('ix_loan_db_users_id'), 'users', ['id'], unique=False, schema='loan_db')
    op.create_index(op.f('ix_loan_db_users_username'), 'users', ['username'], unique=True, schema='loan_db')
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('personal', 'education', 'home', 'vehicle', 'business', name='loanpurpose', schema='loan_db'), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'student', name='employmentstatus', schema='loan_db'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='loanstatus', schema='loan_db'), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['loan_db.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='loan_db'
    )
    op.create_index(op.f('ix_loan_db_loans_id'), 'loans', ['id'], unique=False, schema='loan_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_db_loans_id'), table_name='loans', schema='loan_db')
    op.drop_table('loans', schema='loan_db')
    op.drop_index(op.f('ix_loan_db_users_username'), table_name='users', schema='loan_db')
    op.drop_index(op.f('ix_loan_db_users_id'), table_name='users', schema='loan_db')
    op.drop_index(op.f('ix_loan_db_users_email'), table_name='users', schema='loan_db')
    op.drop_table('users', schema='loan_db')
    # ### end Alembic commands ###
    
    # Drop schema (optional, but keep it for consistency)
    # op.execute('DROP SCHEMA IF EXISTS loan_db CASCADE')
