# tests/test_routing.py
"""Test routing accuracy for 8 different messages."""

from graph.builder import run_graph, initial_state
from observability.langfuse_logger import compare_costs

# The 8-message test script covering various intents.
TEST_MESSAGES = [
    ("I have a question about my invoice.", ["billing"]),
    ("The app gives me an error when I log in.", ["tech"]),
    ("How do I reset my password?", ["account"]),
    ("I need a refund and also need to update my email.", ["billing", "account"]),
    ("Tech support needed, and I also want to view my invoice.", ["tech", "billing"]),
    ("Password reset and technical error.", ["tech", "account"]),
    ("Can you help me with my account and billing refund?", ["billing", "account"]),
    ("Hello, I am just saying hi.", []), # Ambiguous/No match
]

def test_routing_accuracy():
    """Test that the supervisor correctly routes at least 7/8 messages."""
    correct_routes = 0
    
    for msg, expected_intents in TEST_MESSAGES:
        state = initial_state()
        state["messages"] = [{"role": "user", "content": msg}]
        final_state = run_graph(state)
        
        # In our implementation, `executed_agents` was added in the agents,
        # but to verify routing, we can check `pending_intents` right after supervisor,
        # or we can check the `messages` generated by the agents.
        # Alternatively, we can just run the supervisor directly.
        from graph.supervisor import supervisor
        sup_state = initial_state()
        sup_state["messages"] = [{"role": "user", "content": msg}]
        sup_state = supervisor(sup_state)
        
        if sup_state.get("pending_intents", []) == expected_intents:
            correct_routes += 1
            
    assert correct_routes >= 7, f"Routing accuracy too low: {correct_routes}/8"

def run_test():
    """Entry point for main.py to demonstrate the 8-message flow."""
    print("--- Running 8-Message Demo ---")
    for msg, _ in TEST_MESSAGES:
        print(f"\nUser: {msg}")
        state = initial_state()
        state["messages"] = [{"role": "user", "content": msg}]
        final_state = run_graph(state)
        
        # Print assistant messages
        for m in final_state.get("messages", []):
            if m["role"] == "assistant":
                print(f"Assistant: {m['content']}")
        print(f"[Final State next_agent: {final_state.get('next_agent')}]")
        
    print("\n--- Generating Cost Comparison Report ---")
    messages_only = [m[0] for m in TEST_MESSAGES]
    compare_costs(messages_only)
    
    print("\n--- Demo Complete ---")

if __name__ == "__main__":
    run_test()
